name: Construir e enviar imagem do Docker do frontend

on:
  push:
    branches:
      - development
      - docker-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Código de check-out
        uses: actions/checkout@v4

      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extrair metadados
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/angular-lab-web
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Cria e envia a imagem do Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/angular-lab-web:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/angular-lab-web:buildcache,mode=max